spring:
  # 配置服务名
  application:
    name: dataservice
  # 配置数据库信息
  datasource:
    url: jdbc:mysql://localhost:3306/yinglibao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  ## Linux上的5.0版本mysql
    #url: jdbc:mysql://192.168.159.128:3306/yinglibao?useUnicode=true&characterEncoding=UTF-8
    #driverClassName: com.mysql.jdbc.Driver
    #username: root
    #password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # 配置redis
  redis:
    host: localhost
    port: 6379


# 配置dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.dataservice.service
  protocol:
    name: dubbo
  provider:
    timeout: 50000

# 配置mybatis信息
mybatis:
  # #####指定xml映射文件的位置，将接口与xml文件分开管理
  mapper-locations: classpath:mappers/**/*.xml
  # 配置实体类别名
  # type-aliases-package: com.companyname.pojo
  # 配置日志
  configuration:
    # #####配置mybatis日志输入实现类， 输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



